export const FETCH_ALL_NOMINEES_PENDING = "FETCH_ALL_NOMINEES_PENDING";
export const FETCH_ALL_NOMINEES_FULFILLED = "FETCH_ALL_NOMINEES_FULFILLED";
export const FETCH_ALL_NOMINEES_REJECTED = "FETCH_ALL_NOMINEES_REJECTED";

export const VOTE_PENDING = "VOTE_PENDING";
export const VOTE_FULFILLED = "VOTE_FULFILLED";
export const VOTE_REJECTED = "VOTE_REJECTED";
